"""I present the measured figure's typography trials for visual review."""
from pathlib import Path
import json,html
HERE=Path(__file__).resolve().parent
variants=[('diagonal-35-compact','35° · compact','Current main figure. Complete opening excerpts at 7.2 pt and 8.3 inches wide; remaining sentences are in the complete-conversation view.'),('full-dialogue-balanced','Complete conversation','All six passages, with every word retained. Two rows give the longer replies more room. 8.2 pt text at 8.3 inches wide.'),('diagonal-35','35° · wide','Complete opening excerpts, including the mood-ring question. 8.5 pt text at 11.7 inches wide.'),('diagonal-45','45° · wide','The same complete opening excerpts at a steeper angle. 8.5 pt text at 11.7 inches wide.'),('six-full-columns','Six complete columns','All six passages printed in full, in one row. 8.3 pt text at 11.7 inches wide.'),('full-dialogue-two-rows','Equal-width columns','All six passages printed in full in two rows. 8.2 pt text; the unequal reply lengths leave more blank space.')]
items=[]
for key,label,description in variants:
    stem=HERE/'figures/mats-hanan-layouts'/key/key
    if stem.with_suffix('.png').exists():items.append({'key':key,'label':label,'description':description,'png':str(stem.relative_to(HERE))+'.png','pdf':str(stem.relative_to(HERE))+'.pdf','svg':str(stem.relative_to(HERE))+'.svg'})
buttons=''.join(f'<button type="button" data-index="{i}" aria-pressed="{str(i==0).lower()}">{html.escape(x["label"])}</button>' for i,x in enumerate(items))
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MATS figure — layout comparison</title><style>
@font-face{font-family:Termes;src:url('fonts/texgyretermes-regular.otf')}@font-face{font-family:Termes;src:url('fonts/texgyretermes-bold.otf');font-weight:bold}*{box-sizing:border-box}body{margin:0;background:white;color:#222;font:19px/1.45 Termes,Georgia,serif}main{max-width:1220px;margin:auto;padding:26px}h1{font-size:29px;margin:0 0 7px}p{margin:7px 0 14px}a{color:#25445a}nav{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}button{font:17px Termes,Georgia,serif;border:1px solid #999;border-radius:3px;background:white;padding:7px 12px;color:#222;cursor:pointer}button[aria-pressed=true]{background:#eee;border-color:#222;box-shadow:inset 0 -2px #222}button:focus-visible{outline:3px solid #0084d1;outline-offset:2px}.description{max-width:850px}img{display:block;width:100%;height:auto}figure{margin:14px 0}.links{display:flex;gap:18px}.note{font-size:16px;color:#444} .status{font-size:16px} @media(max-width:600px){main{padding:16px}h1{font-size:25px}}
</style></head><body><main><p><a href="README.md">Figure files</a></p><h1>Reasoning-role scores across dialogue formats</h1><p>Compare the text layouts. Every version uses the same 578 measured points per panel, the same axes and the paper’s palette.</p><nav aria-label="Figure layouts">BUTTONS</nav><p id="description" class="description" aria-live="polite"></p><p class="links"><a id="pdf">Vector PDF</a><a id="svg">Vector SVG</a><a href="data/mats-hanan-dialogue-v2/conversation.md">Full transcript and reading note</a></p><figure><a id="image-link"><img id="figure" alt="Three role-probe panels with six corresponding passages from the original Hanan–MATS exchange."></a></figure><p class="note">The complete-conversation views retain every word, with Markdown emphasis rendered as text. Diagonal views use explicitly selected complete opening excerpts. Model-generated advice is quoted as experimental input; the reading note identifies its methodological errors.</p></main><script>const layouts=ITEMS;function show(i){const x=layouts[i];document.getElementById('description').textContent=x.description;document.getElementById('figure').src=x.png;document.getElementById('image-link').href=x.png;document.getElementById('pdf').href=x.pdf;document.getElementById('svg').href=x.svg;document.querySelectorAll('button[data-index]').forEach((b,j)=>b.setAttribute('aria-pressed',j===i?'true':'false'));}document.querySelectorAll('button[data-index]').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.index))));show(0);</script></body></html>'''
(HERE/'mats-layout-gallery.html').write_text(page.replace('BUTTONS',buttons).replace('ITEMS',json.dumps(items)))
(HERE/'data/mats-hanan-dialogue-v2/layout-selection.json').write_text(json.dumps({'selected':'diagonal-35-compact','reason':'Complete opening excerpts at fixed 7.2pt, with 35-degree rotation and no ellipses. Full unabridged alternatives retain every word separately.','variants':items,'data_unchanged':True},indent=2)+'\n')
print({'layouts':len(items),'gallery':str(HERE/'mats-layout-gallery.html')})
